In [1]:
import string
import torch

In [6]:
t = torch.zeros((26, 26), dtype=torch.int)
t

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 0, 0, 0, 0, 0, 0, 

In [7]:
type(t)

torch.Tensor

In [9]:
d = {
    'a': 'aval',
    'b': 'bval',
}
print(len(d))
print(len(d.keys()))

2
2


In [10]:
word = 'abc'
for l1, l2 in zip(word, word[1:]):
    print(f'{l1=}, {l2=}')

l1='a', l2='b'
l1='b', l2='c'


In [15]:
size = 2

t = torch.zeros((size, size), dtype=torch.int)
t[0, 0] = 1
t[0, 1] = 10

t[1, 0] = 2
t[1, 1] = 5

p = torch.zeros((size, size), dtype=torch.float64)

for row in range(size):
    for col in range(size):
        p[row, col] = t[row, col] / t[row].sum()
p

tensor([[0.0909, 0.9091],
        [0.2857, 0.7143]], dtype=torch.float64)

In [17]:
size = 2

x = torch.zeros((size, size), dtype=torch.int)
x[0, 0] = 1
x[0, 1] = 10

x[1, 0] = 2
x[1, 1] = 5

y = torch.zeros((size, size), dtype=torch.float64)

y = x.float().div(x.sum(dim=1, keepdim=True))
y

tensor([[0.0909, 0.9091],
        [0.2857, 0.7143]])